# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  algorithm: sha256
  name_template: SHA256SUMS

changelog:
  skip: True

release:
  draft: true
